name: rsprompter
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.0.5=pyhd3eb1b0_0
  - blas=1.0=mkl
  - brotli-python=1.0.9=py310h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.6.77=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.6=3
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jpeg=9e=h5eee18b_3
  - jupyter_client=8.6.0=py310h06a4308_0
  - jupyter_core=5.7.2=py310h06a4308_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=3.0=h295c915_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.11.1.6=0
  - libcurand=10.3.7.77=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl_fft=1.3.10=py310h5eee18b_0
  - mkl_random=1.2.7=py310h1128e8f_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - numpy-base=2.0.1=py310hb5e798b_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.15=h5eee18b_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - python=3.10.15=he870216_1
  - pytorch=2.1.2=py3.10_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchtriton=2.1.0=py310
  - typing_extensions=4.11.0=py310h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
    - accelerate==1.0.1
    - addict==2.4.0
    - affine==2.4.0
    - albumentations==1.4.0
    - aliyun-python-sdk-core==2.16.0
    - aliyun-python-sdk-kms==2.16.5
    - appdirs==1.4.4
    - attrs==24.2.0
    - brotli==1.0.9
    - certifi==2024.8.30
    - cffi==1.17.1
    - click==8.1.7
    - click-plugins==1.1.1
    - cligj==0.7.2
    - colorama==0.4.6
    - comet-ml==3.47.2
    - comm==0.2.1
    - configobj==5.0.9
    - contourpy==1.3.0
    - crcmod==1.7
    - cryptography==43.0.3
    - cycler==0.12.1
    - debugpy==1.6.7
    - docker-pycreds==0.4.0
    - dulwich==0.22.5
    - einops==0.7.0
    - everett==3.1.0
    - exceptiongroup==1.2.0
    - filelock==3.14.0
    - fonttools==4.54.1
    - fsspec==2024.10.0
    - geodataset==0.2.0
    - geopandas==1.0.1
    - gitdb==4.0.11
    - gitpython==3.1.43
    - gmpy2==2.1.2
    - huggingface-hub==0.26.2
    - idna==3.7
    - imageio==2.36.0
    - importlib==1.0.4
    - importlib-metadata==8.5.0
    - ipykernel==6.29.5
    - ipython==8.27.0
    - jedi==0.19.1
    - jinja2==3.1.4
    - jmespath==0.10.0
    - joblib==1.4.2
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - jupyter-client==8.6.0
    - jupyter-core==5.7.2
    - kiwisolver==1.4.7
    - laspy==2.5.4
    - lazrs==0.6.2
    - lazy-loader==0.4
    - markdown==3.7
    - markdown-it-py==3.0.0
    - markupsafe==2.1.3
    - mat4py==0.6.0
    - matplotlib==3.8.2
    - matplotlib-inline==0.1.6
    - mdurl==0.1.2
    - mkl-fft==1.3.10
    - mkl-random==1.2.7
    - mkl-service==2.4.0
    - mmcv==2.1.0
    - mmengine==0.10.5
    - model-index==0.1.11
    - mpmath==1.3.0
    - nest-asyncio==1.6.0
    - networkx==3.2.1
    - numpy==1.26.4
    - opencv-python==4.10.0.84
    - opencv-python-headless==4.10.0.84
    - opendatalab==0.0.10
    - openmim==0.3.9
    - openxlab==0.1.2
    - ordered-set==4.1.0
    - oss2==2.17.0
    - packaging==24.1
    - pandas==2.2.3
    - peft==0.8.2
    - pillow==10.2.0
    - pip==24.2
    - platformdirs==3.10.0
    - prompt-toolkit==3.0.43
    - protobuf==4.25.5
    - psutil==5.9.0
    - pyarrow==18.0.0
    - pycocotools==2.0.7
    - pycparser==2.22
    - pycryptodome==3.21.0
    - pygments==2.15.1
    - pyogrio==0.10.0
    - pyparsing==3.2.0
    - pyproj==3.7.0
    - pysocks==1.7.1
    - python-box==6.1.0
    - python-dateutil==2.9.0.post0
    - pytz==2023.4
    - pyyaml==6.0.2
    - pyzmq==25.1.2
    - qudida==0.0.4
    - rasterio==1.3.7
    - referencing==0.35.1
    - regex==2024.9.11
    - requests==2.28.2
    - requests-toolbelt==1.0.0
    - rich==13.4.2
    - rpds-py==0.21.0
    - safetensors==0.4.5
    - scikit-image==0.24.0
    - scikit-learn==1.5.2
    - scipy==1.14.1
    - segment-anything==1.0
    - semantic-version==2.10.0
    - sentry-sdk==2.17.0
    - setproctitle==1.3.3
    - setuptools==60.2.0
    - shapely==2.0.1
    - simplejson==3.19.3
    - smmap==5.0.1
    - snuggs==1.4.7
    - sympy==1.13.2
    - tabulate==0.9.0
    - termcolor==2.5.0
    - terminaltables==3.1.10
    - threadpoolctl==3.5.0
    - tifffile==2024.9.20
    - tokenizers==0.15.2
    - tomli==2.0.2
    - torch==2.1.2
    - torchaudio==2.1.2
    - torchvision==0.16.2
    - tornado==6.4.1
    - tqdm==4.65.0
    - traitlets==5.14.3
    - transformers==4.38.1
    - triton==2.1.0
    - typing-extensions==4.11.0
    - tzdata==2024.2
    - urllib3==1.26.20
    - wandb==0.16.3
    - wheel==0.44.0
    - wrapt==1.16.0
    - wurlitzer==3.1.1
    - xmltodict==0.13.0
    - yapf==0.40.2
    - zipp==3.20.2
prefix: /home/XXXX-1/.conda/envs/rsprompter

