root_path: "/network/projects/trees-co2/BCI/BCI_2022_tilessubset_family_full/"

dataset: "bci"  #"quebec_trees" or "quebec_plantations"

save_ckpt_path: "/SAVE_PATH/"
comet: True
comet_project: "trees_bci"
comet_exp_name: 
comet_tags: ["maskrcnn", "pretrained"]
load_ckpt_path:  
model_version: "resnet50"  

batch_size: 4
num_workers: 4

lr: 0.0001
momentum: 0.9
weight_decay: 0.0005

lr_scheduler_step_size: 3
lr_scheduler_gamma: 0.1

num_epochs: 300
save_every_epochs: 20
log_images_every_epochs: 20
num_classes: 32

threshold_score: 0.3

weights_loss:
hierarchical_loss:  #only "quebec_trees" is supported so far

apply_nms: True
percentage: 1

seed: 0

with_dsm: False
val_nms: False
