

root_path:  "/network/projects/trees-co2/quebec_trees_tiles_fullresolution" #"/ROOT_PATH/"

save_ckpt_path: "/SAVE_PATH/"
comet: True
comet_project: "trees_sbl"
comet_exp_name: #"maskrcnn_dsm_train_scratch_max_norm"
comet_tags: ["dsm", "pretrained", "hierarchical", "maskrcnn"]

#select dataset: #"quebec_trees" or "quebec_plantations" or "bci"
dataset: "quebec_trees"

load_ckpt_path: #"/network/projects/trees-co2/maskrcnn/runs_new/quebec_trees_dsm_pretrained_0/best_model.pt"

model_version: "resnet50dsm" #"resnet50scratch"   #resnet50 or resnet50_v2

dsm_normalization: "max"

json_train: "/network/projects/trees-co2/quebec_trees_tiles_fullresolution/merged_annots_dsm_train_new.json"
json_val: "/network/projects/trees-co2/quebec_trees_tiles_fullresolution/merged_annots_dsm_val_new.json"
json_test: "/network/projects/trees-co2/quebec_trees_tiles_fullresolution/merged_annots_dsm_test_new.json"

batch_size: 8
num_workers: 0

lr: 0.0001
momentum: 0.9
weight_decay: 0.0005

lr_scheduler_step_size: 3
lr_scheduler_gamma: 0.1

num_epochs: 200
save_every_epochs: 10
log_images_every_epochs: 10
num_classes: 19

threshold_score: 0.3

apply_nms: True
weights_loss: #empty or indicate list of weights for each class for the weighted cross entropy loss ablation
hierarchical_loss: #empty or "quebec_trees" to run the hierarchical loss ablation on the SBL dataset. This is loss is only implemented for the SBL dataset.

seed: 0  #random seed
percentage: 1
