root_path:  "/network/projects/trees-co2/final_tiles/" #path to folder with json annotation files and tiles folders.

save_ckpt_path: "/SAVE_PATH/"
comet: True
comet_project: "trees_clean"
comet_exp_name:
dataset: "quebec_plantations"
comet_tags: ["maskrcnn", "pretrained", "log weights"]
load_ckpt_path: ""
model_version: "resnet50"

batch_size: 32
num_workers: 4

lr: 0.0001
momentum: 0.9
weight_decay: 0.0005

lr_scheduler_step_size: 3
lr_scheduler_gamma: 0.1

num_epochs: 100
save_every_epochs: 10
log_images_every_epochs: 5
num_classes: 10

threshold_score: 0.3

weights_loss:

apply_nms: True
percentage: 1

seed: 0