root_path: "/network/projects/trees-co2/quebec_trees_tiles_fullresolution"

dataset: "quebec_trees"  #"quebec_trees" or "quebec_plantations" or "bci"

save_ckpt_path: "/SAVE_PATH/"
comet: True
comet_project: "trees_quebec_sbl"
comet_exp_name:
comet_tags: ["maskrcnn", "pretrained"]
load_ckpt_path:
model_version: "resnet50"   #resnet50 or resnet50_v2

batch_size: 4
num_workers: 4

lr: 0.0001
momentum: 0.9
weight_decay: 0.0005

lr_scheduler_step_size: 3
lr_scheduler_gamma: 0.1

num_epochs: 200
save_every_epochs: 10
log_images_every_epochs: 10
num_classes: 19

threshold_score: 0.3

weights_loss: #empty or indicate weights for each class for the weighted cross entropy loss ablation
hierarchical_loss: #empty or "quebec_trees" to run the hierarchical loss ablation on the SBL dataset. This is loss is only implemented for the SBL dataset.

apply_nms: True
percentage: 1

nms_score: 1
with_dsm: False
val_nms: False #this is only used in the ablation study where we modify the default NMS
